### ISSUE TITLE
Colocar URL en la descripción del proyecto

### ISSUE THREAD

**Issue by leocabeza** [firebaseve/site-firebase-venezuela#15]
Algo tipo:

🔗 Sitio Web de la Comunidad Firebase Venezuela 🔥 🇻🇪 http://www.firebase.org.ve/

En lugar de:

🔗 Sitio Web de la Comunidad Firebase Venezuela 🔥 🇻🇪

**Comment by Villanuevand** [comment]
¡Listo! Gracias por la recomendacion...
