### ISSUE TITLE
Enlace de Telegram

### ISSUE THREAD

**Issue by Villanuevand** [firebaseve/site-firebase-venezuela#7]
Actualmente el icono de Telegram contiene el siguiente enlace: 
`https://web.telegram.org/#/im?p=@firebaseVe`

Sería ideal que se implementara este => `https://t.me/firebaseve` Ya que tiene la posibilidad de disernir si existe o no la aplicación instalada  y puede redirigir a  la versión web.

**Comment by tecnosoftware** [comment]
Enlace arreglado
